// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmpVSkVnE9IlPZfqPfxeFVcFJTBAQWo8Y',
    appId: '1:1076198659521:web:e0c8e73107a4a690c94b40',
    messagingSenderId: '1076198659521',
    projectId: 'utsmobilebackend-6385f',
    authDomain: 'utsmobilebackend-6385f.firebaseapp.com',
    storageBucket: 'utsmobilebackend-6385f.firebasestorage.app',
    measurementId: 'G-9MF9GFZLE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9MCgjBwjZ4SVAXfitL4Oj1hbfdETemw4',
    appId: '1:1076198659521:android:ee165bcf00af0c4fc94b40',
    messagingSenderId: '1076198659521',
    projectId: 'utsmobilebackend-6385f',
    storageBucket: 'utsmobilebackend-6385f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeqS8AOZHCQrjy1MKMzJhUQm839SQGN9c',
    appId: '1:1076198659521:ios:4ed53eabc79e9ecec94b40',
    messagingSenderId: '1076198659521',
    projectId: 'utsmobilebackend-6385f',
    storageBucket: 'utsmobilebackend-6385f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeqS8AOZHCQrjy1MKMzJhUQm839SQGN9c',
    appId: '1:1076198659521:ios:4ed53eabc79e9ecec94b40',
    messagingSenderId: '1076198659521',
    projectId: 'utsmobilebackend-6385f',
    storageBucket: 'utsmobilebackend-6385f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmpVSkVnE9IlPZfqPfxeFVcFJTBAQWo8Y',
    appId: '1:1076198659521:web:d0d7523241c4e95ec94b40',
    messagingSenderId: '1076198659521',
    projectId: 'utsmobilebackend-6385f',
    authDomain: 'utsmobilebackend-6385f.firebaseapp.com',
    storageBucket: 'utsmobilebackend-6385f.firebasestorage.app',
    measurementId: 'G-CW1V2BDXJ2',
  );
}
